"""Known English contractions and their spaCy token decompositions.

spaCy's English tokenizer splits contractions into clitics. This module
provides the mapping from token sequences back to surface forms, so
contractions can be treated as MWEs and inducted into the dictionary.
"""

# Maps (token1, token2, ...) as produced by spaCy → conventional written form.
# Only includes contractions where spaCy actually splits them.
CONTRACTIONS: dict[tuple[str, ...], str] = {
    # Negation contractions
    ("ca", "n't"): "can't",
    ("could", "n't"): "couldn't",
    ("did", "n't"): "didn't",
    ("does", "n't"): "doesn't",
    ("do", "n't"): "don't",
    ("had", "n't"): "hadn't",
    ("has", "n't"): "hasn't",
    ("have", "n't"): "haven't",
    ("is", "n't"): "isn't",
    ("must", "n't"): "mustn't",
    ("need", "n't"): "needn't",
    ("ought", "n't"): "oughtn't",
    ("sha", "n't"): "shan't",
    ("should", "n't"): "shouldn't",
    ("was", "n't"): "wasn't",
    ("were", "n't"): "weren't",
    ("wo", "n't"): "won't",
    ("would", "n't"): "wouldn't",
    # Pronoun + auxiliary contractions
    ("I", "'m"): "I'm",
    ("I", "'ll"): "I'll",
    ("I", "'d"): "I'd",
    ("I", "'ve"): "I've",
    ("you", "'re"): "you're",
    ("you", "'ll"): "you'll",
    ("you", "'d"): "you'd",
    ("you", "'ve"): "you've",
    ("he", "'s"): "he's",
    ("he", "'ll"): "he'll",
    ("he", "'d"): "he'd",
    ("she", "'s"): "she's",
    ("she", "'ll"): "she'll",
    ("she", "'d"): "she'd",
    ("it", "'s"): "it's",
    ("it", "'ll"): "it'll",
    ("it", "'d"): "it'd",
    ("we", "'re"): "we're",
    ("we", "'ll"): "we'll",
    ("we", "'d"): "we'd",
    ("we", "'ve"): "we've",
    ("they", "'re"): "they're",
    ("they", "'ll"): "they'll",
    ("they", "'d"): "they'd",
    ("they", "'ve"): "they've",
    ("that", "'s"): "that's",
    ("that", "'ll"): "that'll",
    ("that", "'d"): "that'd",
    ("there", "'s"): "there's",
    ("there", "'ll"): "there'll",
    ("there", "'d"): "there'd",
    ("who", "'s"): "who's",
    ("who", "'ll"): "who'll",
    ("who", "'d"): "who'd",
    ("who", "'ve"): "who've",
    ("what", "'s"): "what's",
    ("what", "'ll"): "what'll",
    ("what", "'d"): "what'd",
    ("what", "'ve"): "what've",
    ("where", "'s"): "where's",
    ("where", "'ll"): "where'll",
    ("where", "'d"): "where'd",
    ("when", "'s"): "when's",
    ("when", "'ll"): "when'll",
    ("when", "'d"): "when'd",
    ("how", "'s"): "how's",
    ("how", "'ll"): "how'll",
    ("how", "'d"): "how'd",
    # Other
    ("let", "'s"): "let's",
}
